QUESTIONS_DB = {
    "python": [
        {"q": "What is the correct file extension for Python files?", "options": [".pt", ".pyth", ".py", ".pyt"], "answer": 2, "difficulty": "Easy", "category": "python", "explanation": "Python sources have a .py extension."},
        {"q": "Which data structure operates on a First-In, First-Out (FIFO) principle in Python?", "options": ["list", "queue.Queue", "dict", "set"], "answer": 1, "difficulty": "Easy", "category": "python", "explanation": "Queues process items in a FIFO manner."},
        {"q": "Which keyword is used to define a function in Python?", "options": ["func", "def", "function", "lambda"], "answer": 1, "difficulty": "Easy", "category": "python", "explanation": "The 'def' keyword is used to declare a function."},
        {"q": "What does the 'yield' keyword do in Python?", "options": ["Returns a final value", "Pauses execution and returns a generator", "Stops a loop", "Defines a lambda"], "answer": 1, "difficulty": "Medium", "category": "python", "explanation": "'yield' produces a sequence of values lazily as a generator."},
        {"q": "What is the time complexity of looking up a value in a Python set?", "options": ["O(n)", "O(n log n)", "O(1)", "O(n^2)"], "answer": 2, "difficulty": "Medium", "category": "python", "explanation": "Set lookups use hashing, giving them O(1) average time complexity."},
        {"q": "Which of these is a mutable data type in Python?", "options": ["tuple", "string", "list", "int"], "answer": 2, "difficulty": "Medium", "category": "python", "explanation": "Lists can be modified in place, making them mutable."},
        {"q": "What does the Global Interpreter Lock (GIL) primarily do in CPython?", "options": ["Allows true multi-threading", "Prevents multiple native threads from executing Python bytecodes at once", "Optimizes garbage collection", "Manages memory allocation"], "answer": 1, "difficulty": "Hard", "category": "python", "explanation": "The GIL ensures only one thread executes Python bytecode concurrently, avoiding race conditions in C memory management."},
        {"q": "What is a metaclass in Python?", "options": ["A class for multiple inheritance", "A class of a class, defining class behavior", "An immutable abstract base class", "A class that decorators inherit from"], "answer": 1, "difficulty": "Hard", "category": "python", "explanation": "A metaclass controls how a class is created, like how a class controls instance creation."},
        {"q": "How does python manage memory?", "options": ["Manual allocation", "Reference counting and cyclical garbage collection", "Mark and sweep alone", "Stack-only allocation"], "answer": 1, "difficulty": "Hard", "category": "python", "explanation": "Python mainly uses reference counting supplemented by a garbage collector to handle reference cycles."}
    ],
    "javascript": [
        {"q": "What keyword declares a variable in JavaScript?", "options": ["variable", "def", "let", "int"], "answer": 2, "difficulty": "Easy", "category": "javascript", "explanation": "Variables are typically declared using let, const, or var."},
        {"q": "How do you check strict equality in JS?", "options": ["==", "===", "=", "!=="], "answer": 1, "difficulty": "Easy", "category": "javascript", "explanation": "The '===' operator checks both value and type for strict equality."},
        {"q": "What represents the absence of a value in JavaScript?", "options": ["null", "undefined", "NaN", "0"], "answer": 0, "difficulty": "Easy", "category": "javascript", "explanation": "'null' represents the intentional absence of any object value."},
        {"q": "Which statement best describes Promises in JS?", "options": ["Sync code blocks", "Represents eventual completion of async operation", "Callback functions only", "Thread management"], "answer": 1, "difficulty": "Medium", "category": "javascript", "explanation": "Promises wrap asynchronous operations and can be resolved or rejected."},
        {"q": "What is closure in JavaScript?", "options": ["Ending a loop", "Function remembering its lexical scope", "Syntax error", "Method of an object"], "answer": 1, "difficulty": "Medium", "category": "javascript", "explanation": "A closure gives you access to an outer function's scope from an inner function."},
        {"q": "Which of these creates a new array with results of calling a function on every array element?", "options": ["filter()", "reduce()", "map()", "forEach()"], "answer": 2, "difficulty": "Medium", "category": "javascript", "explanation": "The map() method creates a new array populated with the results of calling a provided function."},
        {"q": "What does the JS event loop do?", "options": ["Executes sync code off main thread", "Pushes callbacks to the call stack when it is empty", "Initializes the DOM", "Translates JS to machine code"], "answer": 1, "difficulty": "Hard", "category": "javascript", "explanation": "The event loop continuously checks if the call stack is empty to execute queued callback tasks."},
        {"q": "What is the difference between 'apply' and 'call' in JS?", "options": ["apply takes arguments as an array", "call creates a new function", "apply is strictly for arrow functions", "No difference"], "answer": 0, "difficulty": "Hard", "category": "javascript", "explanation": "'apply' takes an array of arguments, while 'call' takes a comma-separated list of arguments."},
        {"q": "What is a characteristic of pure functions?", "options": ["They modify external variables", "They always return the same output for same inputs without side effects", "They require closures", "They use asynchronous callbacks"], "answer": 1, "difficulty": "Hard", "category": "javascript", "explanation": "Pure functions have no side effects and are strictly deterministic."}
    ],
    "html/css": [
        {"q": "What does HTML stand for?", "options": ["Hyper Text Markup Language", "High Text Machine Language", "Hyperlinks Text Mark Language", "Home Tool Markup Language"], "answer": 0, "difficulty": "Easy", "category": "html/css", "explanation": "HTML stands for Hyper Text Markup Language."},
        {"q": "Which HTML tag creates a hyperlink?", "options": ["<link>", "<a>", "<href>", "<url>"], "answer": 1, "difficulty": "Easy", "category": "html/css", "explanation": "The <a> tag defines a hyperlink."},
        {"q": "What property is used in CSS to change text color?", "options": ["font-color", "text-color", "color", "fgcolor"], "answer": 2, "difficulty": "Easy", "category": "html/css", "explanation": "The 'color' property in CSS specifies the color of text."},
        {"q": "What CSS layout module excels at 2D grid systems?", "options": ["Flexbox", "CSS Grid", "Bootstrap", "Floats"], "answer": 1, "difficulty": "Medium", "category": "html/css", "explanation": "CSS Grid Layout is optimized for 2-dimensional layouts (rows and columns)."},
        {"q": "What is the correct CSS syntax to select an element with id 'header'?", "options": [".header", "*header", "#header", "header"], "answer": 2, "difficulty": "Medium", "category": "html/css", "explanation": "The '#' symbol is used to select elements by ID."},
        {"q": "Which HTML5 feature enables persistent local data storage?", "options": ["Cookies", "Session Storage", "Local Storage", "IndexedDB"], "answer": 2, "difficulty": "Medium", "category": "html/css", "explanation": "localStorage stores data with no expiration date."},
        {"q": "What is CSS specificity?", "options": ["How specific a variable name is", "A weight applied to CSS declarations to determine which applies", "The length of the CSS file", "Browser compatibility metrics"], "answer": 1, "difficulty": "Hard", "category": "html/css", "explanation": "Specificity is the algorithm used by browsers to determine the CSS declaration that is most relevant."},
        {"q": "What does setting 'box-sizing: border-box' do?", "options": ["Includes padding and border in the element's total width/height", "Removes borders entirely", "Converts boxes to flex containers", "Forces content out of the box bounds"], "answer": 0, "difficulty": "Hard", "category": "html/css", "explanation": "It tells the browser to account for any border and padding in the values you specify for an element's width and height."},
        {"q": "Which is an example of a pseudo-element?", "options": [":hover", "::before", ":active", ":first-child"], "answer": 1, "difficulty": "Hard", "category": "html/css", "explanation": "::before is a pseudo-element used to insert cosmetic content, whereas :hover is a pseudo-class."}
    ],
    "sql": [
        {"q": "What does SQL stand for?", "options": ["Simple Query Language", "Structured Query Language", "Strong Question Language", "Safe Query Language"], "answer": 1, "difficulty": "Easy", "category": "sql", "explanation": "SQL stands for Structured Query Language."},
        {"q": "Which clause filters records in SQL?", "options": ["ORDER BY", "WHERE", "SELECT", "GROUP BY"], "answer": 1, "difficulty": "Easy", "category": "sql", "explanation": "The WHERE clause restricts the rows affected by a query."},
        {"q": "Which command removes a table in SQL?", "options": ["DELETE", "REMOVE", "DROP", "TRUNCATE"], "answer": 2, "difficulty": "Easy", "category": "sql", "explanation": "The DROP TABLE command completely deletes a table and its structure."},
        {"q": "What does a LEFT JOIN do?", "options": ["Returns only matching rows", "Returns all rows from right table", "Returns all rows from left table", "Errors if no match"], "answer": 2, "difficulty": "Medium", "category": "sql", "explanation": "A LEFT JOIN returns all records from the left table, and matched records from the right table."},
        {"q": "What is a Primary Key?", "options": ["A key given to DB admin", "Unique identifier for a record", "A non-unique index", "A foreign relationship"], "answer": 1, "difficulty": "Medium", "category": "sql", "explanation": "Primary keys must contain unique values ensuring each row can be distinctly identified."},
        {"q": "Which aggregate function returns the highest value?", "options": ["TOP()", "MAX()", "HIGH()", "PEAK()"], "answer": 1, "difficulty": "Medium", "category": "sql", "explanation": "The MAX() SQL function returns the maximum value in a given column."},
        {"q": "What is an index in a database?", "options": ["A table of contents to speed up retrieval", "A security layer", "A foreign key constraint", "A procedure language"], "answer": 0, "difficulty": "Hard", "category": "sql", "explanation": "Indexes are special lookup tables that the database search engine can use to speed up data retrieval."},
        {"q": "What is the ACID property 'Atomicity'?", "options": ["Transactions execute simultaneously", "Tansactions are fully completed or completely rolled back", "Data persists physically", "Connections are isolated"], "answer": 1, "difficulty": "Hard", "category": "sql", "explanation": "Atomicity means 'all or nothing'—either all operations of a transaction succeed, or none do."},
        {"q": "What's the difference between DELETE and TRUNCATE?", "options": ["None", "TRUNCATE removes the table schema", "TRUNCATE is a DDL command that resets identity", "DELETE is irreversible"], "answer": 2, "difficulty": "Hard", "category": "sql", "explanation": "TRUNCATE is a DDL command which drops and recreates the table, resetting identity columns, unlike DELETE."}
    ],
    "general aptitude": [
        {"q": "What is 15% of 200?", "options": ["15", "20", "30", "45"], "answer": 2, "difficulty": "Easy", "category": "general aptitude", "explanation": "15% of 100 is 15, so 15% of 200 is 30."},
        {"q": "If a dozen eggs cost $3, how much do 36 eggs cost?", "options": ["$6", "$9", "$12", "$15"], "answer": 1, "difficulty": "Easy", "category": "general aptitude", "explanation": "36 eggs is 3 dozen. 3 dozen * $3 = $9."},
        {"q": "Which word is out of place?", "options": ["Apple", "Orange", "Tomato", "Carrot"], "answer": 3, "difficulty": "Easy", "category": "general aptitude", "explanation": "Carrot is a root vegetable, whereas the others are classifying fruits botanically."},
        {"q": "If a project takes 4 developers 10 days to complete, how long would it take 8 developers?", "options": ["5 days", "20 days", "10 days", "8 days"], "answer": 0, "difficulty": "Medium", "category": "general aptitude", "explanation": "Doubling the resources halves the time required (assuming linear efficiency)."},
        {"q": "What is the next number in the sequence: 2, 4, 8, 16, ...?", "options": ["24", "32", "64", "20"], "answer": 1, "difficulty": "Medium", "category": "general aptitude", "explanation": "The sequence multiplies each previous number by 2."},
        {"q": "Train A leaves traveling 60 mph. Train B leaves exactly 1 hr later at 80 mph. When does B catch A?", "options": ["2 hrs", "3 hrs", "4 hrs", "5 hrs"], "answer": 1, "difficulty": "Hard", "category": "general aptitude", "explanation": "A is 60 miles ahead. B closes the gap by 20 mph. 60 / 20 = 3 hours."},
        {"q": "A bat and ball cost $1.10. The bat costs $1.00 more than the ball. How much is the ball?", "options": ["$0.10", "$0.05", "$1.00", "$0.15"], "answer": 1, "difficulty": "Hard", "category": "general aptitude", "explanation": "If ball is $0.05, then bat is $1.05, summing up to $1.10."}
    ],
    "default": [
        {"q": "Which data structure operates on a First-In, First-Out (FIFO) principle?", "options": ["Stack", "Queue", "Tree", "Graph"], "answer": 1, "difficulty": "Easy", "category": "computer science", "explanation": "Queues natively support FIFO data retrieval."},
        {"q": "What does a Boolean represent?", "options": ["A number", "True or False state", "A string of text", "A floating point value"], "answer": 1, "difficulty": "Easy", "category": "computer science", "explanation": "Boolean data types take strictly True or False."},
        {"q": "What is a primary purpose of Git?", "options": ["Database Management", "Version Control", "Cloud Hosting", "Compiling Code"], "answer": 1, "difficulty": "Medium", "category": "computer science", "explanation": "Git tracks and versions source code changes across teams."},
        {"q": "What is the time complexity of a perfectly balanced binary search tree lookup?", "options": ["O(n)", "O(n^2)", "O(log n)", "O(1)"], "answer": 2, "difficulty": "Medium", "category": "computer science", "explanation": "The height of a balanced tree is logarithmically proportional to its element count."},
        {"q": "Which design pattern restricts a class to a single instance?", "options": ["Factory", "Observer", "Singleton", "Decorator"], "answer": 2, "difficulty": "Hard", "category": "computer science", "explanation": "The Singleton pattern prevents multiple instantiations globally."}
    ]
}
